/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab7;

import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class NewCD extends javax.swing.JFrame {

    CDManager cdm1 = new CDManager();

    /**
     * Creates new form NewCD
     */
    public NewCD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCdID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCdTitle = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboCdCollection = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        buttonVCD = new javax.swing.JRadioButton();
        buttonCD = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtYearOfRelease = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(7, 1));

        jLabel1.setText("CD ID");
        jPanel1.add(jLabel1);

        txtCdID.setPreferredSize(new java.awt.Dimension(400, 22));
        txtCdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCdIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtCdID);

        getContentPane().add(jPanel1);

        jLabel2.setText("CD Title ");
        jPanel2.add(jLabel2);

        txtCdTitle.setPreferredSize(new java.awt.Dimension(400, 22));
        txtCdTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCdTitleActionPerformed(evt);
            }
        });
        jPanel2.add(txtCdTitle);

        getContentPane().add(jPanel2);

        jLabel3.setText("CD Collection");
        jPanel3.add(jLabel3);

        comboCdCollection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie", "Game", "Music" }));
        jPanel3.add(comboCdCollection);

        jLabel4.setText("CD Type");
        jPanel3.add(jLabel4);

        buttonGroup1.add(buttonVCD);
        buttonVCD.setText("VCD");
        buttonVCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVCDActionPerformed(evt);
            }
        });
        jPanel3.add(buttonVCD);

        buttonGroup1.add(buttonCD);
        buttonCD.setText("CD");
        jPanel3.add(buttonCD);

        getContentPane().add(jPanel3);

        jPanel9.add(jLabel6);

        jLabel7.setText("CD Price");
        jPanel10.add(jLabel7);

        txtPrice.setPreferredSize(new java.awt.Dimension(400, 22));
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel10.add(txtPrice);

        jPanel9.add(jPanel10);

        getContentPane().add(jPanel9);

        jLabel5.setText("CD Year of Release ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel5)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel7);

        txtYearOfRelease.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel5.add(txtYearOfRelease);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdd);
        jPanel5.add(jPanel8);

        getContentPane().add(jPanel5);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCdIDActionPerformed

    private void txtCdTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCdTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCdTitleActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        String type;
        if (checkInput()) {
            if (buttonCD.isSelected()) {
                type = "CD";
            } else {
                type = "VCD";
            }
            cdm1.addCD(txtCdID.getText(), comboCdCollection.getSelectedItem().toString(), type, txtCdTitle.getText(), Double.parseDouble(txtPrice.getText()), Integer.parseInt(txtYearOfRelease.getText()));
            JOptionPane.showMessageDialog(null, "CD added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            clear();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void buttonVCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVCDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed
    private void clear() {
        txtCdID.setText("");
        txtCdTitle.setText("");
        txtPrice.setText("");
        txtYearOfRelease.setText("");
    }

    public boolean checkInput() {
        if (txtCdID.getText().equals("") || txtCdTitle.getText().equals("") || txtPrice.getText().equals("") || txtYearOfRelease.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all information", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            double d = Double.parseDouble(txtPrice.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Please input only numbers as Price", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            double d = Double.parseDouble(txtYearOfRelease.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Please input only numbers as Year", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JRadioButton buttonCD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonVCD;
    private javax.swing.JComboBox<String> comboCdCollection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtCdID;
    private javax.swing.JTextField txtCdTitle;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtYearOfRelease;
    // End of variables declaration//GEN-END:variables
}
